### ISSUE TITLE
Outdated links in a preface chapter

### ISSUE THREAD

**Issue by vsemozhetbyt** [rauschma/exploring-es2018-es2019#10]
1. In the ["The TC39 process for ECMAScript features"](http://exploringjs.com/es2018-es2019/ch_tc39-process.html) there are 2 occurrences of this link:

https://github.com/tc39/ecma262/blob/master/stage0.md

It seems the page has been relocated here:

https://github.com/tc39/proposals/blob/master/stage-0-proposals.md

2. Maybe the link "A readme file with all proposals at stage 1 or higher":

https://github.com/tc39/ecma262/blob/master/README.md

there also can be redefined into:

https://github.com/tc39/proposals/blob/master/README.md

See also this moving PR: https://github.com/tc39/ecma262/pull/567

**Comment by rauschma** [comment]
Fixed now, thanks!
